version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jose
    versions:
    - 3.10.0
    - 3.11.0
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.11.4
    - 3.5.4
    - 3.6.0
    - 3.6.1
    - 3.6.2
    - 3.7.0
    - 3.7.1
    - 3.8.0
    - 3.9.0
  - dependency-name: sinon
    versions:
    - 10.0.0
